apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: dbsql
  labels:
    app: dbsql
spec:
  selector:
    matchLabels:
      app: dbsql
      tier: dbsql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dbsql
        tier: dbsql
    spec:
      containers:
      - image: dilipkumarashok/mysql
        name: dbsql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
